service: default
runtime: python312
# service_account: SERVICE_ACCOUNT@PROJECT_ID.iam.gserviceaccount.com

instance_class: F2
automatic_scaling:
  max_instances: 1

entrypoint: gunicorn -b :$PORT -w 4 -k uvicorn.workers.UvicornWorker main:app
